version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_development
    ports:
      - "3306:3306"
  redis:
    container_name: redismovies
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
  todo-mysql-data:
