version: "3.7"
services:
  redis:
    image: redis:7-bullseye
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - demoapp
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - demoapp

volumes:
  cache:
    driver: local
  todo-mysql-data:
networks:
  demoapp:
# db:
#     image: mysql
#     env_file:
#       - ./.env
#     environment:
#       MYSQL_USER: ${DB_USERNAME}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_DATABASE}
#     ports:
#       - "3306:3306"
#     # networks:
#     #   - demoapp
#     volumes:
#       - todo-mysql-data:/var/lib/mysql
