version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_development
    ports:
      - "3306:3306"

volumes:
  todo-mysql-data:
